# This workflow performs Static Code Analysis and Secrets checks. All findings are reported as issues.

name: Static Code Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build:
    name: Code Analysis
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL,MEDIUM,LOW'
          ignore-unfixed: true
          format: 'json'
          output: 'result.json'
          exit-code: '1'

      - name: Report Findings
        uses: chili-piper/trivy-report-issue-action@PR-Features
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          input-filename: "result.json"
          label: 'vulnerability'
          assignee: ''
          project-id: ''