# Testing to get vars to see how pr info is passed

name: Static Code Analysis

on:
  pull_request:
  
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: | 
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Test Comment from Action!'
            })
