# This workflow performs Static Code Analysis and Secrets checks.

name: Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build:
    name: PR Test
    runs-on: ubuntu-18.04
    env:
      Results: none
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Trivy vulnerability scanner for pull request
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL,MEDIUM,LOW'
          ignore-unfixed: true
          format: 'table'
          output: 'result.tbl'

      - run: |
          echo 'Results<<EOF' >> $GITHUB_ENV
          cat result.tbl >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - uses: actions/github-script@v6
        with:
          script: | 
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Trivy Scan Results <br> ``` ${{ env.Results }}   ```'
            })
